export const GET_CURRENT_WEATHER = 'WEATHER/GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_SUCCESS =
  'WEATHER/GET_CURRENT_WEATHER_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

export const SET_CITY = 'USER/SET_CITY';
export const SET_CITY_SUCCESS = 'USER/SET_CITY_SUCCESS';

export const SET_THEME = 'USER/SET_THEME';
export const SET_THEME_SUCCESS = 'USER/SET_THEME_SUCCESS';

export const GET_CITY = 'USER/GET_CITY';
export const GET_CITY_SUCCESS = 'USER/GET_CITY_SUCCESS';

export const GET_THEME = 'USER/GET_THEME';
export const GET_THEME_SUCCESS = 'USER/GET_THEME_SUCCESS';

export const KEY_FOR_CITY = 'USER/KEY_FOR_CITY';
export const KEY_FOR_THEME = 'USER/KEY_FOR_THEME';
